// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnExZLlX5zzMlouqWUQ_yp5myp-VJN3_4',
    appId: '1:550257165799:web:60335c7638c2da54d7a942',
    messagingSenderId: '550257165799',
    projectId: 'brand-online-ea59d',
    authDomain: 'brand-online-ea59d.firebaseapp.com',
    storageBucket: 'brand-online-ea59d.firebasestorage.app',
    measurementId: 'G-068Y0K1DN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsgPmmGWxc7aXcXxF8KmJ67xy53_YAEA',
    appId: '1:550257165799:android:3e40b4def2df31bbd7a942',
    messagingSenderId: '550257165799',
    projectId: 'brand-online-ea59d',
    storageBucket: 'brand-online-ea59d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOz0fTj4vBk9TammrB5MHaJvyqTlBCeXE',
    appId: '1:550257165799:ios:0259dde53cd2541ed7a942',
    messagingSenderId: '550257165799',
    projectId: 'brand-online-ea59d',
    storageBucket: 'brand-online-ea59d.firebasestorage.app',
    iosBundleId: 'com.brand.online',
  );
}
