// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1S5vlHms8deQOJEZtoTeUWn3_oKV5cs',
    appId: '1:1083691689598:web:419efcd5ea7d35a1d9da2f',
    messagingSenderId: '1083691689598',
    projectId: 'restart-2f2b3',
    authDomain: 'restart-2f2b3.firebaseapp.com',
    storageBucket: 'restart-2f2b3.firebasestorage.app',
    measurementId: 'G-2LTLPNEE0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwn-OwSp9_iOelGP5dMJ3ugJA5YubYSnE',
    appId: '1:1083691689598:android:eeef811d2d9c98d0d9da2f',
    messagingSenderId: '1083691689598',
    projectId: 'restart-2f2b3',
    storageBucket: 'restart-2f2b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2WvY2Zc7oZ6a-FQSWhcJpaNw72MQVYB4',
    appId: '1:1083691689598:ios:adbc57e297293711d9da2f',
    messagingSenderId: '1083691689598',
    projectId: 'restart-2f2b3',
    storageBucket: 'restart-2f2b3.firebasestorage.app',
    iosBundleId: 'com.brand.online',
  );

}